name: unit test on push
on: push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Install Package
      run: pip install pytest
    - name: testing
      run: pytest test.py
